python/one-time-messages/app/models.py
from app import db
from datetime import datetime
import uuid


def _generate_slug():
    return uuid.uuid4().hex


class Message(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    slug = db.Column(db.Text(32), nullable=False, default=_generate_slug, unique=True)
    content = db.Column(db.Text, nullable=False)
    create_timestamp = db.Column(db.DateTime, default=datetime.now())
    expiration_timestamp = db.Column(db.DateTime, default=datetime.min)

python/one-time-messages/app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(config)

    from app.views import views

    app.register_blueprint(views)

    db.init_app(app)
    db.create_all(app=app)

    return app

python/one-time-messages/app/views.py
from flask.blueprints import Blueprint
from flask import request, render_template, make_response
from app.models import Message
from app import db
import datetime
import uuid

views = Blueprint("views", __name__)


@views.route("/")
@views.route("/index")
def index():
    csrf_token = uuid.uuid4().hex
    response = make_response(render_template("index.html", csrf_token=csrf_token))
    response.set_cookie("X-CSRF-Token", csrf_token)
    return response


def _validate_csrf(req):
    cookie_token = req.cookies.get("X-CSRF-Token", None)
    form_csrf = req.form.get("csrf_token", None)
    if (cookie_token == form_csrf) and (cookie_token is not None):
        return True
    return False


@views.route("/create_message", methods=["POST"])
def create_message():
    if _validate_csrf(request):
        content = request.form.get("content", None)
        expiration_timestamp = request.form.get("due_timestamp", None)
        if content:
            message = Message(
                content=content,
            )
            if expiration_timestamp:
                message.due_timestamp = datetime.datetime.strptime(expiration_timestamp, '%Y-%m-%dT%H:%M')
            db.session.add(message)
            db.session.commit()
            response = make_response(render_template("create_message.html", message=message))
            response.delete_cookie("X-CSRF-Token")
            return response
    return "Form data is not valid", 400


@views.route("/message/<slug>")
def display_message(slug):
    message = Message.query.filter_by(slug=slug).first()
    if message:
        db.session.delete(message)
        db.session.commit()
        time_now, time_due = datetime.datetime.now(), message.expiration_timestamp
        if time_now > time_due != datetime.datetime.min:
            return "Message is due", 404
        return render_template("message.html", message=message)
    return "Message not found", 404

python/one-time-messages/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>One-time-messages</title>
    <style>
        nav>a {
            text-decoration: none;
        }
    </style>
</head>
<body>
<nav>
    <a href="/">
        <h3>One-time-messages</h3>
    </a>
</nav>
<hr>
{% block content %}

{% endblock %}
</body>
</html>

python/one-time-messages/app/templates/create_message.html
{% extends "base.html" %}

{% block content %}
    <div>
        <h3>Message created</h3>
        <p>Creation time: {{ message.create_timestamp }}</p>
        <a href="{{ url_for("views.display_message", slug=message.slug) }}">link to message</a>
        <p>or raw link:</p>
        <p>{{ url_for("views.display_message", slug=message.slug, _external=True) }}</p>

    </div>
{% endblock %}

python/one-time-messages/app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <div>
        <h2>Message form</h2>
        <form method="post" action="{{ url_for("views.create_message") }}">
            <input name="csrf_token" hidden value="{{ csrf_token }}">
            <p>Message content</p>
            <textarea name="content" cols="40" rows="10"></textarea>
            <p>Expiration time</p>
            <input name="expiration_timestamp" type="datetime-local">
            <br><br>
            <input type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

python/one-time-messages/app/templates/message.html
{% extends "base.html" %}

{% block content %}
    <div>
        <h2>Message:</h2>
        {% autoescape false %}
        <p>{{ message.content | replace('\n', '<br>') }}</p>
        {% endautoescape %}
        <span>END MESSAGE</span>
    </div>

{% endblock %}